//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weather.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chance of rain.
        /// </summary>
        public static string HubChanceOfRain {
            get {
                return ResourceManager.GetString("HubChanceOfRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like:.
        /// </summary>
        public static string HubFeelsLike {
            get {
                return ResourceManager.GetString("HubFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string HubLowTemp {
            get {
                return ResourceManager.GetString("HubLowTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Weather widget.
        /// </summary>
        public static string OptionsAbout {
            get {
                return ResourceManager.GetString("OptionsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string OptionsAboutTabHeader {
            get {
                return ResourceManager.GetString("OptionsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        public static string OptionsApplyButton {
            get {
                return ResourceManager.GetString("OptionsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string OptionsCancelButton {
            get {
                return ResourceManager.GetString("OptionsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string OptionsCelsius {
            get {
                return ResourceManager.GetString("OptionsCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string OptionsData {
            get {
                return ResourceManager.GetString("OptionsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string OptionsFahrenheit {
            get {
                return ResourceManager.GetString("OptionsFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsGeneralTabHeader {
            get {
                return ResourceManager.GetString("OptionsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h..
        /// </summary>
        public static string OptionsIntervalHours {
            get {
                return ResourceManager.GetString("OptionsIntervalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        public static string OptionsIntervalMinutes {
            get {
                return ResourceManager.GetString("OptionsIntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsItem {
            get {
                return ResourceManager.GetString("OptionsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string OptionsLocation {
            get {
                return ResourceManager.GetString("OptionsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OptionsOkButton {
            get {
                return ResourceManager.GetString("OptionsOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of your location and press search.
        /// </summary>
        public static string OptionsSearchBox {
            get {
                return ResourceManager.GetString("OptionsSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string OptionsSearchButton {
            get {
                return ResourceManager.GetString("OptionsSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;feels like&quot; temperature instead of actual.
        /// </summary>
        public static string OptionsShowFeelsLike {
            get {
                return ResourceManager.GetString("OptionsShowFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show temperature in:.
        /// </summary>
        public static string OptionsShowTempIn {
            get {
                return ResourceManager.GetString("OptionsShowTempIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show weather video in the hub.
        /// </summary>
        public static string OptionsShowVideo {
            get {
                return ResourceManager.GetString("OptionsShowVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string OptionsUI {
            get {
                return ResourceManager.GetString("OptionsUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsVersion {
            get {
                return ResourceManager.GetString("OptionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather refresh interval:.
        /// </summary>
        public static string OptionsWeatherInterval {
            get {
                return ResourceManager.GetString("OptionsWeatherInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshItem {
            get {
                return ResourceManager.GetString("RefreshItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup your location in options. Click to open options..
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
    }
}
